server:
  port: 8080
  
spring:
  application:
    name: api-gateway
    
 
  cloud:
    gateway:
      routes:
      - id: product-service
        uri: 
          lb://product-service
        predicates:
        - Path=/products/**

      - id: profile-service
        uri: 
          lb://profile-service
        predicates:
        - Path=/profile/**
       
      - id: cart-service
        uri: 
          lb://cart-service
        predicates:
        - Path=/cart/**
